name: webfinger
description: A library that implements the WebFinger protocol defined by RFC 7033.
version: 0.1.0
author: Steven Roose <stevenroose@gmail.com>
homepage: http://stevenroose.be
dependencies:
  http: ">=0.11.1+3 <0.12.0"
  webhand:
    path: /home/steven/git/webhand-dart
  xrd: ">=0.1.0 <0.2.0"
dev_dependencies:
  unittest: any
  browser: any
